name: pg # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

system-usernames:
  snap_daemon: shared

layout:
  $SNAP/usr/share/postgresql/14/extension/postgis.control:
    symlink: $SNAP/usr/share/postgresql/14/extension/postgis-3.control
  $SNAP/usr/share/postgresql/14/extension/postgis_raster.control:
    symlink: $SNAP/usr/share/postgresql/14/extension/postgis_raster-3.control

apps:
  postgresql:
    command: start-postgresql.sh
    daemon: simple
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/openblas-pthread:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/lapack"
    install-mode: disable
    restart-condition: always
    plugs:
      - network
      - network-bind

parts:
  pg:
    # See 'snapcraft plugins'
    plugin: nil
    stage-packages:
      - libblas.so.3
      - postgresql
      - postgresql-14-postgis-3
      - util-linux
  wrapper:
    plugin: dump
    source: snap/local
